// File: Display.cpp

#include "Display.h"
#include "hardware/gpio.h"
#include "st7789_lcd.pio.h" // Generated by CMake

// Screen configuration for GMT020-02
constexpr uint16_t PHYSICAL_WIDTH = 240;
constexpr uint16_t PHYSICAL_HEIGHT = 320;
constexpr float SERIAL_CLK_DIV = 1.25f;

static const uint8_t st7789_init_seq[] = {
    1, 20, 0x01,
    1, 10, 0x11,
    2, 2,  0x3a, 0x55,
    2, 0,  0x36, 0x00, // This will be overridden by orientation logic
    5, 0,  0x2a, 0x00, 0x00, (PHYSICAL_WIDTH-1) >> 8, (PHYSICAL_WIDTH-1) & 0xff,
    5, 0,  0x2b, 0x00, 0x00, (PHYSICAL_HEIGHT-1) >> 8, (PHYSICAL_HEIGHT-1) & 0xff,
    1, 2,  0x21,
    1, 2,  0x13,
    1, 2,  0x29,
    0
};

// --- THE FIX: Constructor is now lightweight ---
St7789Display::St7789Display(PIO pio, uint pin_sda, uint pin_scl, uint pin_cs, uint pin_dc, uint pin_reset, DisplayOrientation orientation)
    : m_pio(pio), m_pin_sda(pin_sda), m_pin_scl(pin_scl), m_pin_cs(pin_cs), m_pin_dc(pin_dc), m_pin_reset(pin_reset), m_orientation(orientation)
{
    // It only saves variables and calculates dimensions, no hardware access.
    if (m_orientation == DisplayOrientation::LANDSCAPE) {
        m_width = PHYSICAL_HEIGHT;
        m_height = PHYSICAL_WIDTH;
    } else {
        m_width = PHYSICAL_WIDTH;
        m_height = PHYSICAL_HEIGHT;
    }
}

// --- THE FIX: All hardware setup is moved to init() ---
void St7789Display::init() {
    m_sm = pio_claim_unused_sm(m_pio, true);
    m_offset = pio_add_program(m_pio, &st7789_lcd_program);
    st7789_lcd_program_init(m_pio, m_sm, m_offset, m_pin_sda, m_pin_scl, SERIAL_CLK_DIV);

    uint32_t pin_mask = (1u << m_pin_cs) | (1u << m_pin_dc) | (1u << m_pin_reset);
    gpio_init_mask(pin_mask);
    gpio_set_dir_out_masked(pin_mask);

    gpio_put(m_pin_cs, 1);
    gpio_put(m_pin_reset, 1);
    
    init_display();
}

void St7789Display::init_display() {
    const uint8_t *cmd = st7789_init_seq;
    while (*cmd) {
        send_command(cmd + 2, *cmd);
        sleep_ms(*(cmd + 1) * 5);
        cmd += *cmd + 2;
    }

    uint8_t madctl_data = (m_orientation == DisplayOrientation::LANDSCAPE) ? 0x60 : 0x00;
    uint8_t madctl_cmd[] = {0x36, madctl_data};
    send_command(madctl_cmd, sizeof(madctl_cmd));
    
    uint8_t caset_cmd[] = {
        0x2A, 0x00, 0x00, 
        static_cast<uint8_t>((m_width - 1) >> 8), 
        static_cast<uint8_t>((m_width - 1) & 0xff)
    };
    send_command(caset_cmd, sizeof(caset_cmd));
    
    uint8_t raset_cmd[] = {
        0x2B, 0x00, 0x00, 
        static_cast<uint8_t>((m_height - 1) >> 8), 
        static_cast<uint8_t>((m_height - 1) & 0xff)
    };
    send_command(raset_cmd, sizeof(raset_cmd));
}

void St7789Display::set_dc_cs(bool dc, bool cs) {
    sleep_us(1);
    gpio_put_masked((1u << m_pin_dc) | (1u << m_pin_cs), (dc << m_pin_dc) | (cs << m_pin_cs));
    sleep_us(1);
}

void St7789Display::send_command(const uint8_t *cmd, size_t count) {
    st7789_lcd_wait_idle(m_pio, m_sm);
    set_dc_cs(false, false); // DC low (command), CS low (active)
    st7789_lcd_put(m_pio, m_sm, *cmd++);
    
    if (count > 1) {
        st7789_lcd_wait_idle(m_pio, m_sm);
        set_dc_cs(true, false); // DC high (data), CS low (active)
        for (size_t i = 0; i < count - 1; ++i)
            st7789_lcd_put(m_pio, m_sm, *cmd++);
    }
    
    st7789_lcd_wait_idle(m_pio, m_sm);
    set_dc_cs(true, true); // DC high, CS high (inactive)
}

void St7789Display::fillScreen(uint16_t color) {
    drawBuffer(0, 0, m_width, m_height, nullptr, color);
}

void St7789Display::drawBuffer(uint16_t x, uint16_t y, uint16_t width, uint16_t height, const uint16_t* buffer, uint16_t fillColor) {
    uint8_t cmd_caset[] = {0x2A, static_cast<uint8_t>(x >> 8), static_cast<uint8_t>(x), static_cast<uint8_t>((x + width - 1) >> 8), static_cast<uint8_t>(x + width - 1)};
    send_command(cmd_caset, sizeof(cmd_caset));

    uint8_t cmd_raset[] = {0x2B, static_cast<uint8_t>(y >> 8), static_cast<uint8_t>(y), static_cast<uint8_t>((y + height - 1) >> 8), static_cast<uint8_t>(y + height - 1)};
    send_command(cmd_raset, sizeof(cmd_raset));

    uint8_t cmd_ramwr = 0x2C;
    send_command(&cmd_ramwr, 1);

    set_dc_cs(true, false); // Data mode, chip selected

    if (buffer) {
        for (uint32_t i = 0; i < width * height; ++i) {
            st7789_lcd_put(m_pio, m_sm, buffer[i] >> 8);
            st7789_lcd_put(m_pio, m_sm, buffer[i] & 0xff);
        }
    } else {
        for (uint32_t i = 0; i < width * height; ++i) {
            st7789_lcd_put(m_pio, m_sm, fillColor >> 8);
            st7789_lcd_put(m_pio, m_sm, fillColor & 0xff);
        }
    }

    st7789_lcd_wait_idle(m_pio, m_sm);
    set_dc_cs(true, true); // Inactive
}