// File: Display.cpp

#include "Display.h"
#include "hardware/gpio.h"
#include "st7789_lcd.pio.h" // Generated by CMake

// Screen configuration for GMT020-02 (240x320 Portrait) ---
constexpr uint16_t SCREEN_WIDTH = 240;
constexpr uint16_t SCREEN_HEIGHT = 320;
constexpr float SERIAL_CLK_DIV = 1.25f; // Results in 100MHz pixel clock

// Command sequence for ST7789 240x320 displays ---
static const uint8_t st7789_init_seq[] = {
    1, 20, 0x01,                        // Software reset
    1, 10, 0x11,                        // Exit sleep mode
    2, 2,  0x3a, 0x55,                   // Set colour mode to 16 bit
    2, 0,  0x36, 0x00,                   // Set MADCTL for portrait mode (Top-to-Bottom, Left-to-Right)
    5, 0,  0x2a, 0x00, 0x00, (SCREEN_WIDTH-1) >> 8, (SCREEN_WIDTH-1) & 0xff,   // CASET
    5, 0,  0x2b, 0x00, 0x00, (SCREEN_HEIGHT-1) >> 8, (SCREEN_HEIGHT-1) & 0xff, // RASET
    1, 2,  0x21,                         // Inversion on
    1, 2,  0x13,                         // Normal display on
    1, 2,  0x29,                         // Main screen turn on
    0                                   // Terminate list
};

St7789Display::St7789Display(PIO pio, uint pin_din, uint pin_clk, uint pin_cs, uint pin_dc, uint pin_reset, uint pin_bl)
    : m_pio(pio), m_pin_din(pin_din), m_pin_clk(pin_clk), m_pin_cs(pin_cs), m_pin_dc(pin_dc), m_pin_reset(pin_reset), m_pin_bl(pin_bl) 
{
    m_sm = pio_claim_unused_sm(m_pio, true);
    m_offset = pio_add_program(m_pio, &st7789_lcd_program);
    st7789_lcd_program_init(m_pio, m_sm, m_offset, m_pin_din, m_pin_clk, SERIAL_CLK_DIV);

    gpio_init(m_pin_cs);
    gpio_init(m_pin_dc);
    gpio_init(m_pin_reset);
    gpio_init(m_pin_bl);

    gpio_set_dir(m_pin_cs, GPIO_OUT);
    gpio_set_dir(m_pin_dc, GPIO_OUT);
    gpio_set_dir(m_pin_reset, GPIO_OUT);
    gpio_set_dir(m_pin_bl, GPIO_OUT);

    gpio_put(m_pin_cs, 1);
    gpio_put(m_pin_reset, 1);
    
    init_display();
    
    gpio_put(m_pin_bl, 1);
}

void St7789Display::set_dc_cs(bool dc, bool cs) {
    sleep_us(1);
    gpio_put_masked((1u << m_pin_dc) | (1u << m_pin_cs), (dc << m_pin_dc) | (cs << m_pin_cs));
    sleep_us(1);
}

void St7789Display::send_command(const uint8_t *cmd, size_t count) {
    st7789_lcd_wait_idle(m_pio, m_sm);
    set_dc_cs(false, false); // DC low (command), CS low (active)
    st7789_lcd_put(m_pio, m_sm, *cmd++);
    
    if (count > 1) {
        st7789_lcd_wait_idle(m_pio, m_sm);
        set_dc_cs(true, false); // DC high (data), CS low (active)
        for (size_t i = 0; i < count - 1; ++i)
            st7789_lcd_put(m_pio, m_sm, *cmd++);
    }
    
    st7789_lcd_wait_idle(m_pio, m_sm);
    set_dc_cs(true, true); // DC high, CS high (inactive)
}

void St7789Display::init_display() {
    const uint8_t *cmd = st7789_init_seq;
    while (*cmd) {
        send_command(cmd + 2, *cmd);
        sleep_ms(*(cmd + 1) * 5);
        cmd += *cmd + 2;
    }
}

void St7789Display::fillScreen(uint16_t color) {
    drawBuffer(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, nullptr, color);
}

void St7789Display::drawBuffer(uint16_t x, uint16_t y, uint16_t width, uint16_t height, const uint16_t* buffer, uint16_t fillColor) {
    uint8_t cmd_caset[] = {0x2A, (uint8_t)(x >> 8), (uint8_t)x, (uint8_t)((x + width - 1) >> 8), (uint8_t)(x + width - 1)};
    send_command(cmd_caset, sizeof(cmd_caset));

    uint8_t cmd_raset[] = {0x2B, (uint8_t)(y >> 8), (uint8_t)y, (uint8_t)((y + height - 1) >> 8), (uint8_t)(y + height - 1)};
    send_command(cmd_raset, sizeof(cmd_raset));

    uint8_t cmd_ramwr = 0x2C;
    send_command(&cmd_ramwr, 1);

    set_dc_cs(true, false); // Data mode, chip selected

    if (buffer) {
        for (uint32_t i = 0; i < width * height; ++i) {
            st7789_lcd_put(m_pio, m_sm, buffer[i] >> 8);
            st7789_lcd_put(m_pio, m_sm, buffer[i] & 0xff);
        }
    } else {
        for (uint32_t i = 0; i < width * height; ++i) {
            st7789_lcd_put(m_pio, m_sm, fillColor >> 8);
            st7789_lcd_put(m_pio, m_sm, fillColor & 0xff);
        }
    }

    st7789_lcd_wait_idle(m_pio, m_sm);
    set_dc_cs(true, true); // Inactive
}